options:
  formatter: stylish
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - 'src/assets/scss/base/_fonts.scss'
    - 'src/assets/scss/vendors/_foundation.scss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 2
  no-combinators: 0
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    -
      extra-properties:
        - caret-color
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 2
  property-units: 0

  # Nesting
  declarations-before-nesting: 2
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2

  # Name Formats
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  function-name-format: 2
  id-name-format: 0
  mixin-name-format: 2
  placeholder-name-format: 2
  variable-name-format: 2

  # Style Guide
  attribute-quotes: 2
  bem-depth: 0
  border-zero: 2
  brace-style: 2
  clean-import-paths: 0
  empty-args: 2
  hex-length: 2
  hex-notation: 2
  indentation:
    - 2
    -
      size: 4
  leading-zero: 2
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth:
    - 2
    - max-depth: 3
  property-sort-order:
    - 2
    -
      order:
      - position
      - top
      - right
      - bottom
      - left
      - z-index
      - box-sizing
      - display
      - flex
      - flex-align
      - flex-basis
      - flex-direction
      - flex-wrap
      - flex-flow
      - flex-grow
      - flex-order
      - flex-pack
      - align-items
      - align-self
      - justify-content
      - float
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - overflow
      - overflow-x
      - overflow-y
      - clip
      - clear
      - font
      - font-family
      - font-size
      - font-style
      - font-weight
      - font-variant
      - font-size-adjust
      - font-stretch
      - font-effect
      - font-emphasize
      - font-emphasize-position
      - font-emphasize-style
      - font-smooth
      - hyphens
      - line-height
      - color
      - text-align
      - text-align-last
      - text-emphasis
      - text-emphasis-color
      - text-emphasis-style
      - text-emphasis-position
      - text-decoration
      - text-indent
      - text-justify
      - text-outline
      - text-overflow
      - text-overflow-ellipsis
      - text-overflow-mode
      - text-shadow
      - text-transform
      - text-wrap
      - letter-spacing
      - word-break
      - word-spacing
      - word-wrap
      - overflow-wrap
      - tab-size
      - white-space
      - vertical-align
      - list-style
      - list-style-position
      - list-style-type
      - list-style-image
      - pointer-events
      - touch-action
      - cursor
      - visibility
      - zoom
      - table-layout
      - empty-cells
      - caption-side
      - border-spacing
      - border-collapse
      - content
      - quotes
      - counter-reset
      - counter-increment
      - resize
      - user-select
      - nav-index
      - nav-up
      - nav-right
      - nav-down
      - nav-left
      - background
      - background-color
      - background-image
      - filter
      - background-repeat
      - background-attachment
      - background-position
      - background-position-x
      - background-position-y
      - background-clip
      - background-origin
      - background-size
      - border
      - border-color
      - border-style
      - border-width
      - border-top
      - border-top-color
      - border-top-style
      - border-top-width
      - border-right
      - border-right-color
      - border-right-style
      - border-right-width
      - border-bottom
      - border-bottom-color
      - border-bottom-style
      - border-bottom-width
      - border-left
      - border-left-color
      - border-left-style
      - border-left-width
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-right-radius
      - border-bottom-left-radius
      - border-image
      - border-image-source
      - border-image-slice
      - border-image-width
      - border-image-outset
      - border-image-repeat
      - outline
      - outline-width
      - outline-style
      - outline-color
      - outline-offset
      - box-shadow
      - opacity
      - transition
      - transition-delay
      - transition-timing-function
      - transition-duration
      - transition-property
      - transform
      - transform-origin
      - animation
      - animation-name
      - animation-duration
      - animation-play-state
      - animation-timing-function
      - animation-delay
      - animation-iteration-count

  pseudo-element: 2
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
